;;;  defvar-packages.el --- -*- lexical-binding: t; -*-

(defvar nord-theme-load-p t)
(defvar solarized-theme-load-p t)
(defvar mac-modifiers-load-p t)
(defvar expand-region-load-p t)
(defvar pass-load-p t)
(defvar smartparens-load-p t)
(defvar rainbow-delimiters-load-p t)
(defvar doom-modeline-load-p t)
(defvar all-the-icons-load-p t)
(defvar smart-comment-load-p t)
(defvar bufler-load-p t)
(defvar dired-subtree-load-p t)
(defvar helpful-load-p t)
(defvar lsp-load-p t)
(defvar markdown-server-load-p t)
(defvar ace-window-load-p t)
(defvar perspective-load-p t)
(defvar pdf-tools-load-p t)
(defvar rg-load-p t)
(defvar whole-line-or-region-load-p t)
(defvar completion-framework-load-p t)
(defvar mediator-load-p t)
(defvar affe-load-p t)
(defvar vterm-load-p t)
(defvar god-mode-load-p t)

(provide 'defvar-packages)
